# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_92-7oM72DrIcxjoLjnAxYFbr47ltV4

# Assignment 2
Let's test your knowledge!

_____
**Use <code>for</code>, .split(), and <code>if</code> to create a Statement that will print out words that start with 's':**

st = 'Print only the words that start with s in this sentence'
"""



#Code here
st = 'Print only the words that start with s in this sentence'
st=st.split()#[print,only,the,words,that,..etc]
for word in st:
    if word[0] == 's':
        print(word)



"""______
**Use range() to print all the even numbers from 0 to 10.**
"""

for i in range(0,11):
    if i%2==0:
        print(i)

"""___
**Use a List Comprehension to create a list of all numbers between 1 and 50 that are divisible by 3.**
"""

#Code Here
list1 = [x for x in range(1, 51) if x % 3 == 0]
print(list1)

"""_____
**Go through the string below and if the length of a word is even print "even!"**
"""

st = 'Print every word in this sentence that has an even number of letters'

#Code in this cell
st=st.split()
for i in range (0,len(st)):
    if(i%2==0):
        print('even')

"""____
**Write a program that prints the integers from 1 to 100. But for multiples of three print "Fizz" instead of the number, and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".**
"""

#Code in this cell
for i in range(0,101):
    if (i%3 ==0) & (i%5==0):
        print("FizzBuzz")
    elif i%3==0 :
        print("Fizz")
    else : 
        print("Buzz")

"""____
**Use List Comprehension to create a list of the first letters of every word in the string below:**
"""

st = 'Create a list of the first letters of every word in this string'

#Code in this cell
st = [word[0] for word in st.split()]
print(st)

"""### Great Job!"""