# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktDbzMHImVpHTLCka6cmVOINYETVRJYD

# Assignment 3

### Write a function to count the number 4 in a given list.
"""

x=[1,2,3,4,4,4]
def count(x):
    sum =0
    for i in x:# hena bya5od bylf 3la value as a value msh index
        if i==4:
            sum+=1
    print(sum)

count(x)

"""### write a  function to check whether a number is divisible by another number."""

def checker (x,y):
    if (x%y==0):
        print(" {} is divisible by {}".format(x,y))
    else:
        print(" {} is not divisible by {}".format(x,y))
checker(5,6)

"""### write a function to find the maximum and minimum numbers from a sequence of numbers."""

z=[1,2,3,4,5]
def checker2 (x):
    small=x[0]
    large=x[0]
    for i  in x :# indexing loop 
        if i>large:
            large=i
        elif i< small:
            small=i
    return small,large
print(checker2(z))

"""### Write a Python function that takes two lists and returns True if they have at least one common member."""

def in_common(c,d):
        for i in c:
            for z in d :
                if (i==z):
                    return ("true")
            
x=[1,2,3,4]
y=[4,4,2,3]
            
in_common(x,y)

"""### Write a Python function to calculate the factorial of a number (a non-negative integer). The function accepts the number from the user"""

def factorial (x):
    if (x==1) or (x==0) :
        return 1
    else:
        return x*factorial(x-1)
  
y=int(input("please enter the number"))
print(factorial(y))

def fac(n):
  return 1 if (n==1 or n==0) else n
fac(5)

"""### Write a Python function to check whether a number is in a given range.

### The range is from 3 to 11

"""

x=3
def checker3(x):
    if x in range(3,12) :
        print ("true")
checker3(x)

"""### Write a  program to create the multiplication table (from 1 to 10) of a number."""

def multp(x):
    for i in range (1,11):
        multp=x*i
        print(multp)
    
multp(4)

"""#### LESSER OF TWO EVENS: Write a function that returns the lesser of two given numbers *if* both numbers are even, but returns the greater if one or both numbers are odd
    lesser_of_two_evens(2,4) --> 2
    lesser_of_two_evens(2,5) --> 5
"""

def lesser_of_two_evens (x,y):
    if(x%2==0) and (y%2==0):
        if(x>y):
            return(y)
        else:
            return(x)
    else:
        if (x>y):
            print(x)
        else:
            print(y)

lesser_of_two_evens(2,5)
lesser_of_two_evens(2,4)

"""#### ANIMAL CRACKERS: Write a function takes a two-word string and returns True if both words begin with same letter
    animal_crackers('Levelheaded Llama') --> True
    animal_crackers('Crazy Kangaroo') --> False
"""

def animal_crackers(x):
    x=x.split()
    if(x[0][0]==x[1][0]):
        print("true")
    elif(x[0][0]!=x[1][0]):
        print("false")
animal_crackers('Crazy Kangaroo')

"""#### MAKES TWENTY: Given two integers, return True if the sum of the integers is 20 *or* if one of the integers is 20. If not, return False

    makes_twenty(20,10) --> True
    makes_twenty(12,8) --> True
    makes_twenty(2,3) --> False
"""

def makes_twenty(x,y):
    if(x+y==20) or (x==20) or(y==20):
        return True
    else :
        return False
makes_twenty(20,10)
makes_twenty(12,8)
makes_twenty(2,3)

"""#### ALMOST THERE: Given an integer n, return True if n is within 10 of either 100 or 200

    almost_there(90) --> True
    almost_there(104) --> True
    almost_there(150) --> False
    almost_there(209) --> True
    
NOTE: `abs(num)` returns the absolute value of a number
"""

almost_there=lambda x: (abs(100-x)<=10) or (abs(200-x)<=10)
almost_there(150)

"""#### BLACKJACK: Given three integers between 1 and 11, if their sum is less than or equal to 21, return their sum. If their sum exceeds 21 *and* there's an eleven, reduce the total sum by 10. Finally, if the sum  exceeds 21, return 'BUST'
    blackjack(5,6,7) --> 18
    blackjack(9,9,9) --> 'BUST'
    blackjack(9,9,11) --> 19
"""

def blackjack (x,y,z):
    if (x,y,z in range (1,12)):
        if((x+y+z)<=21):
            return x+y+z
        elif(x+y+z>21)and((x==11)or(y==11)or(z==11)):
            return (x+y+z)-10
        elif (x+y+z>21):
            return 'BUST'
        
blackjack(5,6,7)          
blackjack(9,9,9)     
blackjack(9,9,11)

