# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y9Pd8IsHNmc9lW_GTTwkk501QTg5n0sX

# Assignment 1

## Test your knowledge. 

** Answer the following questions **

## Strings

Given the string 'hello' give an index command that returns 'e'. Enter your code in the cell below:
"""

s = 'hello'
# Print out 'e' using indexing
s[1]

"""Reverse the string 'hello' using slicing:"""

s ='hello'
# Reverse the string using slicing
s[::-1]

"""Given the string hello, give two methods of producing the letter 'o' using indexing."""

s ='hello'
# Print out the 'o'
# Method 1:
print(s[4])

# Method 2:
s[-1]

"""## Lists

Build this list [0,0,0] two separate ways.
"""

# Method 1:
l=[0,0,0]
l

# Method 2:
l=[0]*3
print(l) 
#or
lis = list()
lis.append(0)
lis.append(0)
lis.append(0)
lis

"""Reassign 'hello' in this nested list to say 'goodbye' instead:"""

list3 = [1,2,[3,4,'hello']]
list3[2][2]='goodbye'
list3

"""Sort the list below:"""

list4 = [5,3,4,6,1]
list4.sort()
list4

"""## Dictionaries

Using keys and indexing, grab the 'hello' from the following dictionaries:
"""

d = {'simple_key':'hello'}
# Grab 'hello'
d['simple_key']

d = {'k1':{'k2':'hello'}}
# Grab 'hello'
d['k1']['k2']

d = {'k1':[{'nest_key':['this is deep',['hello']]}]}

#Grab hello
d['k1'][0]['nest_key'][1]

d = {'k1':[1,2,{'k2':['this is tricky',{'tough':[1,2,['hello']]}]}]}
#Grab hello
d['k1'][2]['k2'][1]['tough'][2]









"""** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742
print("the diameter of {} is {} kilometers".format(planet,diameter))

"""** Given this nested list, use indexing to grab the word "hello" **"""

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst[3][1][2]

"""** Given this nested dictionary grab the word "hello". **"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d['k1'][3]['tricky'][3]['target'][3]

"""### Write a Python program to swap two variables.

"""

x=3
y=4
z=x
x=y
y=z
print(x,y)

"""## Thanks"""