# -*- coding: utf-8 -*-
"""Mini-projec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBD8HZJnDeUyd-rf1tDqDrsaQ5K4TWcq
"""



"""##Mini-project:


➔ Create aCalculator
Ask the user to enter a command "add","sub","mult","div" and two
numbers to simulate a calculator.

"""

def add(a,b):
  addition=a+b
  return addition

def sub(a,b):
  subb=a-b
  return subb

def mult(a,b):
  multt=a*b
  return multt

def div(a,b):
  divv=a/b
  return divv



x=float(input("please enter 2 numbers\n"))
y=float(input())
c=input("please enter your operation ")

if (c=='add') :
 print(add(x,y)) 
elif (c=='sub'):
  print(sub(x,y))
elif (c=='mult'):
  print(mult(x,y))
elif (c=="div"):
  print(div(x,y))
else :
  print("error")